baseURL = "http://localhost/"

title = "config.anlu.me"
theme = "hugo-book"
copyright = "Andy Luo"

disablePathToLower = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    languageName = "English"
    weight = 1

[outputFormats]
  [outputFormats.txt]
    mediaType = "text/plain"
    baseName = "source"
    isPlainText = true

[outputs]
  home = ["html", "rss"]
  page = ["html"]
  section = ["html", "txt"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
  [markup.highlight]
    noClasses = false
    tabWidth = 2
    guessSyntax = true

[params]
  BookTheme = "auto"
  BookSection = "docs"
  BookToC = true
  BookSearch = true
  BookDateFormat = "January 2, 2006"
  BookPortableLinks = true
  BookRepo = "https://github.com/andy-y-luo/config.anlu.me"

[menu]
  [[menu.home]]
    name = "Docs"
    pageRef = "/docs"
    weight = 1
  [[menu.home]]
    name = "Repo"
    url = "https://github.com/andy-y-luo/config.anlu.me"
    weight = 10
