#+title: Tmux Configuration
#+setupfile: ../headers
#+property: header-args:conf  :mkdirp yes :lexical t :exports code
#+property: header-args:conf+ :tangle ~/.config/tmux/tmux.conf
#+property: header-args:conf+ :mkdirp yes :noweb no-export

* Tmux Configuration

** Introduction
I'm using Tmux to run multiple terminal sessions inside a single window. The session persistence feature is nice, and I can juggle multiple workstreams at once through it.

Literate configuration for [[https://github.com/tmux/tmux][Tmux]]. The single source file tangles to =~/.config/tmux/tmux.conf=.

** General / Base Settings

*** Terminal / mouse behavior
I want to be able to scroll, resize, switch panes/wins with the mouse.
#+begin_src conf
set -g mouse on
#+end_src

Set correct $TERM for colors & keybindings.
#+begin_src conf
set -g default-terminal "tmux-256color"
#+end_src

*** Prefix key
Remap prefix from ~C-b~ to ~C-a~ for easier reach.
#+begin_src conf
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
#+end_src

*** Reload
Reload the config on the fly so changes don't require restarting tmux.
#+begin_src conf
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"
#+end_src

*** Pane behavior
Intuitive split commands using ~|~ and ~-~.
#+begin_src conf
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
#+end_src

Switching panes happens frequently, I don't want to trigger the prefix key all the time. I'll use ~M-<direction>~ to go where I want.
#+begin_src conf
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
#+end_src

Start pane numbering at ~1~.
#+begin_src conf
set-option -g pane-base-index 1
#+end_src

*** Window behaviour
Don't rename windows automatically; start window numbering at ~1~.
#+begin_src conf
set-option -g allow-rename off
set-option -g base-index 1
#+end_src

=allow-rename off= stops tmux from renaming on its own; =set-titles off=
stops tmux from forwarding shell OSC sequences (zsh, fish, etc.) to the
outer terminal.
#+begin_src conf
set -g set-titles off
#+end_src

*** Status line
The bottom-of-screen status bar. Left-align the window names. Overall, I want a
clean, minimal status line. Nothing flashy or distracting. It should convey just
the right amount of useful information.
#+begin_src conf
set -g status-justify left
#+end_src

=status-left= shows the session name; =status-right= shows a "Z"
when the active pane is zoomed followed by the current key mode
(via =tmux-mode-indicator= plugin).

I want the colors to follow  the terminal theme: =bg= / =fg= use the terminal default; the
session name uses the terminal's =green= accent; the zoom "Z" uses
the terminal's =red= accent.
#+begin_src conf
set -g status-left-length 32
set -g status-left  ' #[fg=green,bold]#S '
set -g status-right ' #{?window_zoomed_flag,#[fg=red]Z ,}#{tmux_mode_indicator} '
set -g status-style 'bg=default,fg=default'
#+end_src

In the window list, the current window is wrapped in brackets; all
windows use the default style. Nice and simple.
#+begin_src conf
setw -g window-status-format         ' #I:#W#F '
setw -g window-status-current-format ' [#I:#W#F]'
#+end_src

*** Plugin manager (TPM)
TPM is installed once per machine, outside this config:
#+begin_src sh
git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
#+end_src

Declare plugins to load. Press ~prefix + I~ to install, ~prefix + U~ to
update, ~prefix + M-u~ to remove.
#+begin_src conf
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'
#+end_src

Mode indicator styles, again following the principle of adhereing to terminal theme.
It uses the same background as the rest of the status line, text color is the only
thing that changes between modes.
#+begin_src conf
set -g @mode_indicator_prefix_mode_style 'fg=blue,bg=default'
set -g @mode_indicator_copy_mode_style   'fg=yellow,bg=default'
set -g @mode_indicator_sync_mode_style   'fg=red,bg=default'
set -g @mode_indicator_empty_mode_style  'fg=green,bg=default'
#+end_src

Initialize TPM. This must be the last line of the config so bindings
from installed plugins are picked up.
#+begin_src conf
run '~/.config/tmux/plugins/tpm/tpm'
#+end_src
